---
project_name: auth_exporter

builds:
  - env: 
      - CGO_ENABLED=0
    goos: 
      - linux
    goarch:
      - 386
      - amd64
    flags: "-trimpath"
    ldflags: "-s -w -X main.version={{ .Version }}"
    main: .

archives:
  - id: auth_exporter
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

