language: go

os: linux

go: 
  - tip # The latest version of Go.

install:
   - go get github.com/mattn/goveralls

script:
 - make build
 - curl -sfL https://git.io/goreleaser | sh -s -- check

after_success:
 - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci

deploy:
- provider: script
  cleanup: false
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux